server:
  port: 3344

spring:
  application:
    name: cloud-config-server #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/coffeecw/microservicecloud-config.git #GitHub仓库地址
          #搜索目录
          search-paths:
            - microservicecloud-config
          #读取分支
      label: master
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
